#!/usr/bin/env bash

set -o errexit -o pipefail -o nounset

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

info() {
  echo -e "$@" >&2
}

run_cmd() {
  info "$@"
  "$@"
}

theme="$SCRIPT_DIR/themes/Adwaita-Labwc"
dest="$HOME/.local/share/themes"

run_cmd mkdir -p "$dest"
run_cmd ln -sf "$theme" "$dest"
